// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- OpenNext creates this module after Next.js compilation.
// @ts-ignore `.open-next/worker.js` is generated by OpenNext during build.
import handler from "./.open-next/worker.js";
import { SupportChatRoom } from "./workers/support-chat-room";

type WorkerEnv = {
  SUPPORT_CHAT: DurableObjectNamespace<SupportChatRoom>;
};

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/api/support/ws") {
      const room = env.SUPPORT_CHAT.get(env.SUPPORT_CHAT.idFromName("global"));
      return room.fetch(request);
    }
    return handler.fetch(request, env as never, ctx);
  },
} satisfies ExportedHandler<WorkerEnv>;

export { SupportChatRoom };
