import { generatedTranslations } from "@/lib/i18n-generated";

export const locales = ["en", "zh", "ja", "ko", "es", "de", "pt", "ru", "id", "hi"] as const;
export type Locale = (typeof locales)[number];
export const LOCALE_COOKIE = "game3dtech_locale";

export const localeMeta: Record<Locale, { name: string; short: string; flag: string; htmlLang: string }> = {
  en: { name: "English", short: "EN", flag: "GB", htmlLang: "en" },
  zh: { name: "简体中文", short: "中", flag: "CN", htmlLang: "zh-CN" },
  ja: { name: "日本語", short: "JA", flag: "JP", htmlLang: "ja" },
  ko: { name: "한국어", short: "KO", flag: "KR", htmlLang: "ko" },
  es: { name: "Español", short: "ES", flag: "ES", htmlLang: "es" },
  de: { name: "Deutsch", short: "DE", flag: "DE", htmlLang: "de" },
  pt: { name: "Português", short: "PT", flag: "BR", htmlLang: "pt-BR" },
  ru: { name: "Русский", short: "RU", flag: "RU", htmlLang: "ru" },
  id: { name: "Bahasa Indonesia", short: "ID", flag: "ID", htmlLang: "id" },
  hi: { name: "हिन्दी", short: "HI", flag: "IN", htmlLang: "hi" },
};

export const enMessages = {
  language: "Language", displayCurrency: "Display currency", close: "Close", search: "Search", searchProducts: "Search products…", submitSearch: "Submit search", clearSearch: "Clear search",
  leaderboard: "Best sellers", myOrders: "My orders", wallet: "Balance & top-up", admin: "Admin", logout: "Sign out", login: "Sign in", websiteIcon: "Website icon", clickMe: "Click me", toggleTheme: "Change theme", lightTheme: "Light", darkTheme: "Dark", systemTheme: "System",
  allProducts: "All products", noProducts: "No products yet", comeBackLater: "Please check back later", viewProduct: "View product: {name}", popular: "Popular", soldOut: "Sold out", wantRestock: "Want a restock?", view: "View", sold: "{count} sold", onlyLeft: "Only {count} left",
  home: "Home", backHomePage: "Back to home", categoryNotFound: "Category not found", categoryProducts: "Products in {name}", emptyCategory: "No products in this category", productsComingSoon: "Products are coming soon", productNotFound: "Product not found", inStockSold: "{stock} in stock · {sold} sold", temporarilyOut: "Temporarily out of stock", restockPriority: "Request a restock and we will prioritize stock based on demand.", productDetails: "Product details", userAvatar: "User avatar",
  footerDisclaimer: "This site is not affiliated with Linux DO.", footerTagline: "Digital products and intelligent services", footerSecurePayment: "Secure payment", footerFastDelivery: "Fast delivery", footerMultilingual: "Multilingual", footerNavigation: "Store information", footerTerms: "Terms", footerPrivacy: "Privacy", footerRefunds: "Refund policy", acceptedPayments: "Accepted payment methods",
  loginTitle: "Sign in or create an account", loginDescription: "Sign in to buy products, view orders, and manage your balance", orEmail: "or use Email", register: "Register", password: "Password", nickname: "Display name", confirmPassword: "Confirm password", emailLogin: "Sign in with Email", loggingIn: "Signing in…", creating: "Creating…", createAccount: "Create account", verifyAndLogin: "Verify and sign in", verifying: "Verifying…", back: "Back", resend: "Resend", sending: "Sending…", codeSentTo: "A verification code was sent to {email}. It expires in 10 minutes.", verificationCode: "6-digit verification code",
  passwordLength: "{min}–{max} characters", passwordClasses: "At least 3 of uppercase, lowercase, numbers, and symbols", passwordIdentity: "Does not contain your email name or display name", passwordMismatch: "Passwords do not match", completeCaptcha: "Complete the security check first", securityVerified: "Security check complete", captchaUnavailable: "Turnstile is not configured. Email registration is unavailable.", invalidCredentials: "Incorrect email or password",
  availableBalance: "Available balance", topupAmount: "Top-up amount", topupNow: "Top up now", balanceHistory: "Balance history", balanceHistoryDescription: "Latest 50 balance changes", noBalanceRecords: "No balance records", balanceAfter: "Balance {amount}", invalidPaymentLink: "Invalid payment link",
  ordersTitle: "My orders", ordersDescription: "View purchases, payment status, and delivery details", noOrders: "No orders yet", orderNo: "Order number", product: "Product", amount: "Amount", status: "Status", createdAt: "Created", paidAt: "Paid", actions: "Actions", details: "Details", previous: "Previous", next: "Next",
  receiptUnavailable: "Unable to retrieve payment receipt", tryAgainLater: "Please try again later", paymentReceipt: "Payment receipt", refresh: "Refresh", copy: "Copy", copyFailed: "Copy failed", copied: "Copied", pending: "Pending", paid: "Paid", completed: "Completed", expired: "Expired", refunded: "Refunded", refundPending: "Refund under review", refundRejected: "Refund rejected",
  cancelled: "Cancelled", orderCancelled: "Order cancelled", orderCancelledHint: "The locked inventory has been released and this order can no longer be paid.",
  guestCheckoutTitle: "Buy without registering", guestCheckoutHint: "Order and delivery notifications will be sent to this email.", guestLoginBenefits: "Sign in to use balance, points, and vouchers.", guestOrderEmail: "Order email", memberRechargeBenefitTitle: "Member top-up benefit", memberRechargeBenefit: "Create an account and get 1% bonus credit on every balance top-up.", memberRechargeBenefitShort: "Top up +1%", memberRechargeBenefitHint: "Balance payments can also use points and vouchers.", joinMembership: "Create account", checkoutCaptchaUnavailable: "Security verification is temporarily unavailable. Please sign in to buy.", checkoutAgreement: "By placing an order, you agree to", selectVariant: "Select option", selectedVariant: "Selected: {name}", availableUnits: "{count} available", variantOutOfStock: "Out of stock", finalAmountByVariant: "The final amount is based on the selected option and quantity.", continuePayment: "Continue payment", cancelOrder: "Cancel order", cancelOrderTitle: "Cancel this pending order?", cancelOrderDescription: "The locked inventory will be released immediately and this order can no longer be paid.", keepOrder: "Keep order", confirmCancelOrder: "Confirm cancellation", cannotOpenPayment: "Unable to open the payment page.",
  loadingOrder: "Loading order…", fetchingOrder: "Retrieving order information", signInToViewOrder: "Sign in to view order and delivery details", invalidOrderNo: "Invalid order number", invalidOrderHint: "Return from the payment page or view your order history in My orders.", orderUnavailable: "Unable to retrieve order", savingOrderNo: "Keep the order number for future enquiries", orderInfo: "Order information", placedAt: "Placed", deliveryInfo: "Delivery information", copyAll: "Copy all", refreshStatus: "Refresh status",
  deliveryReady: "Delivery details are ready. Save them securely.", deliveryPreparing: "Payment received. Delivery details are being prepared…", confirmingPayment: "Confirming payment", awaitingPayment: "Waiting for payment", autoUpdateHint: "This usually updates automatically within 30 seconds…", manualRefreshHint: "If you have paid, refresh or check My orders later.", orderExpired: "Order expired", orderExpiredHint: "Payment was not completed in time.", refundProcessing: "Refund processing", refundSubmitted: "Your refund request was submitted for review.", refundRejectedHint: "Contact the administrator or check the order notes if you have questions.", orderRefunded: "Order refunded", orderRefundedHint: "This order has been refunded.", statusUpdating: "Order status updating", statusUpdatingHint: "Refresh later or check My orders for the latest status.", sensitiveDeliveryHint: "Delivery details are sensitive. Be careful where you paste or save screenshots.", preparingDeliveryHint: "Delivery details are being prepared. Refresh shortly or check My orders.", requestRefund: "Request refund", refundReason: "Refund reason", refundDialogHint: "Describe the reason. An administrator will review your request.", refundReasonPlaceholder: "Describe the reason in at least 5 characters", cancel: "Cancel", submitRequest: "Submit request", orderPendingHint: "Payment is pending. Please complete it soon.",
  receiptSubtitle: "For support verification and sharing (no delivery secrets)", verificationInfo: "Verification details", username: "Username", receiptDisclaimer: "This receipt is for information and sharing only. Final verification uses the platform order and admin records.", verifyBeforeSharing: "Verify the information before sharing (no delivery secrets)", copyLink: "Copy link", copyText: "Copy text", downloadPoster: "Download poster", exporting: "Exporting…", link: "Link", receiptTextCopied: "Receipt text copied", linkCopied: "Share link copied", downloadStarted: "Poster download started", exportFailed: "Export failed. Use a screenshot or copy the link instead.",
  searchTitle: "Search products", searchDescription: "Search product names, descriptions, or details", allCategories: "All categories", keyword: "Keyword", category: "Category", enterKeyword: "Enter a keyword to start searching", searchHint: "Try a product name, tag, or use case.", searchMin: "Enter at least 2 characters for better results.", noSearchResults: "No matching products", resultCount: "{count} results · Page {page}/{pages}", relevance: "Relevance", sales: "Sales", newest: "Newest", priceLow: "Price ↑", priceHigh: "Price ↓",
  rank: "Rank", customer: "Customer", completedOrders: "Completed orders", totalSpent: "Total spent", leaderboardDescription: "Products ranked by completed sales", noData: "No data",
  buyNow: "Buy now", outOfStock: "Out of stock", quantity: "Quantity", total: "Total", payWithBalance: "Pay with balance", submitOrder: "Submit order", submitting: "Submitting…", loginRequired: "Please sign in first", orderCreated: "Order created", paymentResult: "Payment result", paymentSuccess: "Payment successful", paymentPending: "Payment pending", paymentFailed: "Payment failed", backHome: "Back to store", viewOrders: "View orders", signInToBuy: "Sign in to purchase", signedInAs: "Signed in as {name}. Your delivery details will appear in My orders after payment.", paymentMethod: "Payment method", onlinePayment: "Online payment", accountBalance: "Account balance", purchaseLimit: "Limit {min}–{max}", processing: "Processing…", orderNumberValue: "Order number: {number}", orderFailed: "Could not place order",
  loading: "Loading…", imagePrevious: "Previous image", imageNext: "Next image", imageOf: "Image {index} of {total}", announcementDetails: "View details", previousAnnouncement: "Previous announcement", nextAnnouncement: "Next announcement", closeAnnouncement: "Close announcement",
  customerReviews: "Customer reviews", basedOnReviews: "Based on {count} verified reviews", noReviews: "No reviews yet", verifiedPurchase: "Verified purchase", merchantReply: "Store reply", writeReview: "Write a review", selectOrder: "Purchased order", rating: "Rating", reviewContent: "Review", reviewPlaceholder: "Share your real experience (5–1000 characters)", publishReview: "Publish review", reviewPublished: "Review published", purchaseToReview: "Complete a purchase of this product to leave a review.", loginToReview: "Sign in to review a completed purchase.", yourReviews: "Your reviews", editReview: "Edit", deleteReview: "Delete", reviewUpdated: "Review updated", reviewDeleted: "Review deleted", hiddenByAdmin: "This review is hidden from the public", loadMoreReviews: "Load more reviews", stars: "{count} stars",
  restockLogin: "Sign in to request a restock", restockRequested: "Restock requested", requestRestock: "Request restock", requestRestockFailed: "Could not request a restock", peopleRequested: "{count} requested", noRestockRequests: "No requests yet", moreRequesters: "{count} more people requested", requesterAvatar: "{name}'s avatar",
  profile: "Profile", voucherRedeem: "Redeem voucher", accountSecurity: "Account & security", forgotPassword: "Forgot password?", email: "Email", sendVerificationCode: "Send code", completeVerification: "Verify email", changeEmail: "Change email", emailCodeSent: "Verification code sent to {email}",
  bindEmailTitle: "Bind email", bindEmailDescription: "Used for order and account security notifications.", resetPassword: "Reset password", resetPasswordDescription: "Enter your verified email and we will send a verification code.", resetPasswordSentDescription: "Enter the verification code and set a new password.", newPassword: "New password", currentPassword: "Current password", confirmNewPassword: "Confirm new password", showPassword: "Show password", hidePassword: "Hide password",
  profileDescription: "Manage the display name and avatar shown in the store", publicProfile: "Public profile", publicProfileDescription: "A customized name and avatar will no longer be overwritten by third-party sign-in data.", currentAvatar: "Current avatar", avatar: "Avatar", chooseImage: "Choose image", avatarFileHint: "JPG, PNG, or WebP, up to 2 MB", invalidAvatarType: "Choose a JPG, PNG, or WebP image", avatarTooLarge: "Avatar must be no larger than 2 MB", boundEmail: "Bound email", saveProfile: "Save profile",
  securityTitle: "Account & security", securityDescription: "Manage your password and sign-in verification", passwordSection: "Password", passwordUpdateHint: "Use a strong password and update it regularly", passwordCreateHint: "Set a local password for this third-party sign-in account", passwordClassesShort: "Contains at least 3 character types", updatePassword: "Update password", setPassword: "Set password", twoFactorTitle: "Two-factor authentication", twoFactorEnabledStatus: "Enabled · {count} recovery codes remaining", twoFactorDescription: "Use an authenticator app to generate one-time codes", saveRecoveryCodes: "Save these recovery codes now", recoveryCodesHint: "Each code can be used once to sign in if you lose access to your authenticator.", recoveryCodesCopied: "Recovery codes copied", copyRecoveryCodes: "Copy recovery codes", configureAuthenticator: "Set up authenticator app", scanAuthenticatorQr: "Scan with Google Authenticator, Microsoft Authenticator, or 1Password", manualSecret: "Can't scan? Enter this key manually:", authenticatorCodeLabel: "Enter the 6-digit code from your authenticator", enableTwoFactor: "Enable", disableTwoFactorHint: "Enter an authenticator code or recovery code before disabling.", twoFactorCodeOrRecovery: "6-digit code or recovery code", disableTwoFactor: "Disable two-factor authentication", verifyTwoFactorTitle: "Two-factor authentication", verifyTwoFactorDescription: "Enter an authenticator code or recovery code to continue.", verifyAndContinue: "Verify and continue",
  walletTitle: "Balance & top-up", walletDescription: "Manage balance, top-up bonuses, and membership points", cnyAccountMember: "CNY account · Member {number}", cashBalance: "Cash balance", bonusBalance: "Bonus credit", memberPoints: "Member points", lifetimeSpend: "Lifetime spend {amount}", distanceToTier: "To {tier}", highestTier: "Highest tier", amountRemaining: "{amount} remaining", unlocked: "Unlocked", membershipProgress: "Membership progress", topupBalance: "Top up balance", topupBalanceHint: "Use it for store payments as soon as it arrives", topupBonusCurrent: "This top-up earns 1% bonus credit", topupAutoCredit: "Your balance is credited automatically after payment", externalPurchase: "Buy on partner platforms", externalPurchaseHint: "Buy a voucher and redeem it under “Redeem voucher”.", topupBenefit: "Top-up bonus", topupBenefitDescription: "Get an extra 1% bonus credit on every top-up.", pointsDiscount: "Points discount", pointsDiscountDescription: "Earn 1 point per ¥1 paid; 200 points save ¥1, up to 10% per order.", accountActivity: "Account activity", accountActivityDescription: "Recent balance and membership changes", memberBenefits: "Membership benefits", noBenefitRecords: "No membership activity yet", balanceLabel: "Balance", tierStarter: "Black Iron", tierSilver: "Silver Radiance", tierGold: "Gold Radiance", tierObsidian: "Obsidian",
  voucherTitle: "Redeem voucher", voucherDescription: "Enter a voucher bought from a partner platform and redeem it for balance or products.", voucherCode: "Voucher code", redeemNow: "Redeem now", rechargeVoucher: "Top-up voucher", rechargeVoucherDescription: "Credit is added immediately", productVoucher: "Product voucher", productVoucherDescription: "Redeem the specified product", discountVoucher: "Discount voucher", discountVoucherDescription: "Saved to your account for checkout", myVouchers: "My vouchers", myVouchersDescription: "Redeemed vouchers and their status.", noVouchers: "No redeemed vouchers", voucherCreditAmount: "{amount} credited", specifiedProduct: "Specified product", voucherDiscountDetail: "Spend {minimum}, save {discount}", voucherExpired: "Expired", voucherReady: "Available", voucherReserved: "Order in progress", voucherUsed: "Used", validUntil: "Valid until {date}",
  guestCheckoutRequired: "Enter an order email and complete the security check to buy", usePoints: "Use points ({count} available)", pointsRule: "200 points save ¥1, up to 10% per order", noDiscountVoucher: "Do not use a discount voucher", voucherApplied: "{amount} saved on this order", voucherAmountRemaining: "Spend {amount} more to use it", voucherDiscountApplied: "Voucher applied: −{amount}", deliveryProtected: "Delivery details are protected by two-factor authentication", verifyToView: "Verify to view",
  imagePreview: "Image preview", imagePreviewDescription: "View the product image enlarged. Press Escape to close.", productImage: "Product image", announcementGoTo: "Go to announcement {index}", settledAs: "Settled as", startsAt: "from",
  previewTitle: "Temporary product preview", previewExpires: "This preview does not publish the product or allow purchases. It expires at {date}.", featured: "Featured", previewUnavailable: "Purchasing is unavailable in preview mode",
  storeMetaTitle: "{site} - Digital Goods Store", storeMetaDescription: "Buy digital goods, software, and AI services securely on {site}.",
  termsTitle: "Terms of Service", termsIntro: "These terms explain the basic rules for browsing, purchasing digital goods, and using account services on Game3DTech.", termsAccountTitle: "Account and information", termsAccountBody: "Provide accurate and valid account and contact information, and keep your sign-in credentials secure. Platform records govern activity on your account.", termsDeliveryTitle: "Products and delivery", termsDeliveryBody: "Product pages show prices, options, expected delivery methods, and stock status. Review the description before payment and check and store digital goods securely after delivery.", termsPaymentTitle: "Payments and balance", termsPaymentBody: "Payment, balance top-up, and spending records are available in your account. If an order status does not match your payment, keep the order number and contact support.", termsUseTitle: "Acceptable use", termsUseBody: "Do not use this site for fraud, abuse, system attacks, or infringement of third-party rights. Violations may result in suspended orders or account restrictions.",
  privacyTitle: "Privacy Notice", privacyIntro: "We process only the information needed to provide accounts, orders, payments, delivery, and support.", privacyCollectionTitle: "Information we collect", privacyCollectionBody: "This includes sign-in identifiers, verified email, order and balance records, support conversations, and basic technical logs needed for security. Third-party sign-in only provides information shown on its authorization page.", privacyPurposeTitle: "How we use it", privacyPurposeBody: "We use information for authentication, order fulfillment, payment verification, important notices, support, fraud prevention, and service improvement. We do not send marketing spam without separate consent.", privacyRetentionTitle: "Retention and protection", privacyRetentionBody: "We retain required records for business, security, and compliance needs and use access controls to limit unauthorized access. Do not send passwords, full payment credentials, or unnecessary sensitive information in support messages.", privacyChoicesTitle: "Your choices", privacyChoicesBody: "You can manage profile and security settings in your account. Contact support to request access, correction, or deletion of relevant information.",
  refundTitle: "Refund and Support Policy", refundIntro: "Because digital goods may be delivered instantly and can be copied, support requests are reviewed against product and delivery status.", refundSubmitTitle: "Submit a request", refundSubmitBody: "After signing in, choose the order under “My orders”, submit a refund request, and explain the reason. You can also provide the order number and details through support.", refundUndeliveredTitle: "Not yet delivered", refundUndeliveredBody: "Unpaid or undelivered orders are reviewed against payment status, reserved stock, and order progress.", refundDeliveredTitle: "Already delivered", refundDeliveredBody: "Displayed, copied, or sent digital keys and benefits usually cannot be recovered. If an item cannot be used, differs from its description, or was charged twice, submit evidence promptly for order-by-order review.", refundResultTitle: "Outcome", refundResultBody: "Review progress and results are recorded on the order. Approved refunds are returned through the original payment channel or account balance; arrival time depends on the payment provider.", legalUpdated: "Updated: July 19, 2026", backToStore: "Back to store",
  supportChat: "Chat", supportQuestion: "Questions? Talk to us", supportOnline: "Support is online", supportAway: "Away · usually replies within an hour", supportConnecting: "Connecting…", supportWelcome: "Hi! How can we help with {site}?", supportPlaceholder: "Type your message…", sendMessage: "Send message", openSupport: "Open customer support", closeChat: "Close chat", minimizeChat: "Minimize chat", realtimeConnected: "Live connection", realtimeDisconnected: "Reconnecting…",
} as const;
export type MessageKey = keyof typeof enMessages;

export const zhMessages: Record<MessageKey, string> = {
  language:"语言",displayCurrency:"显示货币",close:"关闭",search:"搜索",searchProducts:"搜索商品…",submitSearch:"提交搜索",clearSearch:"清空搜索",leaderboard:"热销榜",myOrders:"我的订单",wallet:"余额与充值",admin:"管理后台",logout:"退出登录",login:"登录",websiteIcon:"网站图标",clickMe:"点我一下",toggleTheme:"切换主题",lightTheme:"浅色",darkTheme:"深色",systemTheme:"跟随系统",
  allProducts:"全部商品",noProducts:"暂无商品",comeBackLater:"请稍后再来看看吧",viewProduct:"查看商品：{name}",popular:"热门",soldOut:"已售罄",wantRestock:"想要补货？",view:"查看",sold:"已售 {count}",onlyLeft:"仅剩 {count}",footerDisclaimer:"本站与 Linux DO 官方无任何关系",footerTagline:"数字商品与智能服务交易平台",footerSecurePayment:"安全支付",footerFastDelivery:"快速交付",footerMultilingual:"多语言服务",footerNavigation:"商城信息",footerTerms:"服务条款",footerPrivacy:"隐私说明",footerRefunds:"退款与售后",acceptedPayments:"支持的支付方式",
  home:"首页",backHomePage:"返回首页",categoryNotFound:"分类未找到",categoryProducts:"{name} 分类商品",emptyCategory:"该分类暂无商品",productsComingSoon:"商品即将上架，敬请期待",productNotFound:"商品未找到",inStockSold:"库存 {stock} · 已售 {sold}",temporarilyOut:"商品暂时缺货",restockPriority:"你可以先催补货，我们会根据需求优先补充库存。",productDetails:"商品详情",userAvatar:"用户头像",
  loginTitle:"登录或创建账号",loginDescription:"登录后可购买商品、查询订单和管理余额",orEmail:"或使用 Email",register:"注册",password:"密码",nickname:"昵称",confirmPassword:"确认密码",emailLogin:"Email 登录",loggingIn:"登录中…",creating:"创建中…",createAccount:"创建账号",verifyAndLogin:"验证并登录",verifying:"验证中…",back:"返回",resend:"重新发送",sending:"发送中…",codeSentTo:"验证码已发送至 {email}，10 分钟内有效。",verificationCode:"6 位验证码",passwordLength:"{min}–{max} 个字符",passwordClasses:"大写、小写、数字、特殊字符中至少 3 类",passwordIdentity:"不包含邮箱名前缀或昵称",passwordMismatch:"两次输入的密码不一致",completeCaptcha:"请先完成人机验证",securityVerified:"验证完成",captchaUnavailable:"Turnstile 未配置，Email 注册暂不可用。",invalidCredentials:"Email 或密码错误",
  availableBalance:"可用余额",topupAmount:"充值金额",topupNow:"立即充值",balanceHistory:"余额明细",balanceHistoryDescription:"最近 50 条资金变动",noBalanceRecords:"暂无余额记录",balanceAfter:"余额 {amount}",invalidPaymentLink:"支付链接无效",
  ordersTitle:"我的订单",ordersDescription:"查看购买记录、支付状态与交付内容",noOrders:"暂无订单",orderNo:"订单号",product:"商品",amount:"金额",status:"状态",createdAt:"创建时间",paidAt:"支付时间",actions:"操作",details:"详情",previous:"上一页",next:"下一页",
  receiptUnavailable:"无法获取支付凭证",tryAgainLater:"请稍后重试",paymentReceipt:"支付成功凭证",refresh:"刷新",copy:"复制",copyFailed:"复制失败",copied:"已复制",pending:"待支付",paid:"已支付",completed:"已完成",expired:"已过期",refunded:"已退款",refundPending:"退款审核中",refundRejected:"退款已拒绝",
  cancelled:"已取消",orderCancelled:"订单已取消",orderCancelledHint:"锁定库存已经释放，该订单不能再继续付款。",
  guestCheckoutTitle:"无需注册，填写邮箱即可购买",guestCheckoutHint:"订单链接与发货通知会发送到该邮箱。",guestLoginBenefits:"登录后可使用余额、积分和优惠券。",guestOrderEmail:"接收订单的邮箱",memberRechargeBenefitTitle:"会员充值权益",memberRechargeBenefit:"注册后充值余额，每次额外获得 1% 奖励金。",memberRechargeBenefitShort:"注册充值返 1%",memberRechargeBenefitHint:"使用余额支付时，还可使用积分和优惠券。",joinMembership:"注册会员",checkoutCaptchaUnavailable:"人机验证暂不可用，请登录后购买。",checkoutAgreement:"下单即表示同意",selectVariant:"选择规格",selectedVariant:"已选：{name}",availableUnits:"可用 {count} 件",variantOutOfStock:"缺货",finalAmountByVariant:"最终金额以所选规格和数量合计为准。",continuePayment:"继续支付",cancelOrder:"取消订单",cancelOrderTitle:"取消这个待支付订单？",cancelOrderDescription:"取消后会立即释放已锁定的库存，这个订单不能再继续付款。",keepOrder:"暂不取消",confirmCancelOrder:"确认取消",cannotOpenPayment:"无法打开支付页面。",
  loadingOrder:"加载订单中…",fetchingOrder:"正在获取订单信息",signInToViewOrder:"登录后才能查看订单与卡密信息",invalidOrderNo:"订单号无效",invalidOrderHint:"请从支付页面返回，或在“我的订单”中查看历史订单",orderUnavailable:"无法获取订单",savingOrderNo:"请妥善保存订单号以便查询",orderInfo:"订单信息",placedAt:"下单时间",deliveryInfo:"卡密信息",copyAll:"复制全部",refreshStatus:"刷新状态",
  deliveryReady:"卡密已发放，请及时保存",deliveryPreparing:"订单已支付，卡密发放中…",confirmingPayment:"正在确认支付状态",awaitingPayment:"等待支付完成",autoUpdateHint:"通常会在 30 秒内自动更新，请稍候…",manualRefreshHint:"如果你已完成支付，可点击刷新或稍后查看“我的订单”。",orderExpired:"订单已过期",orderExpiredHint:"该订单未在有效期内完成支付。",refundProcessing:"退款处理中",refundSubmitted:"你的退款申请已提交，正在等待审核。",refundRejectedHint:"如有疑问，请联系管理员或查看订单备注。",orderRefunded:"订单已退款",orderRefundedHint:"该订单已完成退款。",statusUpdating:"订单状态更新中",statusUpdatingHint:"请稍后刷新或前往“我的订单”查看最新状态。",sensitiveDeliveryHint:"卡密属于敏感信息，复制或截图后请注意粘贴范围与聊天记录留存。",preparingDeliveryHint:"卡密发放中，请稍后刷新，或前往“我的订单”查看。",requestRefund:"申请退款",refundReason:"退款原因",refundDialogHint:"请填写退款原因，提交后将由管理员审核",refundReasonPlaceholder:"请详细描述退款原因（至少5个字符）",cancel:"取消",submitRequest:"提交申请",orderPendingHint:"订单待支付，请尽快完成支付",
  receiptSubtitle:"用于客服核验和对外分享（不包含卡密）",verificationInfo:"核验信息",username:"用户名",receiptDisclaimer:"该凭证仅用于信息展示与便捷分享，最终核验以平台订单与后台记录为准。",verifyBeforeSharing:"分享前请确认信息无误（不包含卡密）",copyLink:"复制链接",copyText:"复制文本",downloadPoster:"下载海报",exporting:"导出中…",link:"链接",receiptTextCopied:"已复制凭证文本",linkCopied:"已复制分享链接",downloadStarted:"已开始下载海报",exportFailed:"导出失败，请改用截图或复制链接。",
  searchTitle:"搜索商品",searchDescription:"搜索商品名称、描述或详情内容",allCategories:"全部分类",keyword:"关键词",category:"分类",enterKeyword:"请输入关键词开始搜索",searchHint:"请输入商品名称、标签或用途。",searchMin:"请输入至少 2 个字符以获得更准确的结果。",noSearchResults:"未找到相关商品",resultCount:"共 {count} 条结果 · 第 {page}/{pages} 页",relevance:"相关度",sales:"销量",newest:"最新",priceLow:"价格↑",priceHigh:"价格↓",
  rank:"排名",customer:"顾客",completedOrders:"完成订单",totalSpent:"累计消费",leaderboardDescription:"按已完成订单的商品销量排序",noData:"暂无数据",
  buyNow:"立即购买",outOfStock:"库存不足",quantity:"数量",total:"合计",payWithBalance:"使用余额支付",submitOrder:"提交订单",submitting:"提交中…",loginRequired:"请先登录",orderCreated:"订单已创建",paymentResult:"支付结果",paymentSuccess:"支付成功",paymentPending:"等待支付",paymentFailed:"支付失败",backHome:"返回商城",viewOrders:"查看订单",signInToBuy:"请登录后购买商品",signedInAs:"已登录为 {name}，支付完成后可在“我的订单”查看卡密",paymentMethod:"支付方式",onlinePayment:"在线支付",accountBalance:"账户余额",purchaseLimit:"限购 {min}–{max} 件",processing:"处理中…",orderNumberValue:"订单号：{number}",orderFailed:"下单失败",
  loading:"加载中…",imagePrevious:"上一张图片",imageNext:"下一张图片",imageOf:"第 {index}/{total} 张图片",announcementDetails:"查看详情",previousAnnouncement:"上一条公告",nextAnnouncement:"下一条公告",closeAnnouncement:"关闭公告",
  customerReviews:"商品评价",basedOnReviews:"来自 {count} 条真实购买评价",noReviews:"暂无评价",verifiedPurchase:"已购",merchantReply:"商家回复",writeReview:"发表评价",selectOrder:"购买订单",rating:"评分",reviewContent:"评价内容",reviewPlaceholder:"分享真实使用体验（5–1000 个字符）",publishReview:"发布评价",reviewPublished:"评价已发布",purchaseToReview:"完成该商品订单后即可发表评价。",loginToReview:"登录后可评价已完成的订单。",yourReviews:"我的评价",editReview:"编辑",deleteReview:"删除",reviewUpdated:"评价已更新",reviewDeleted:"评价已删除",hiddenByAdmin:"该评价暂未公开展示",loadMoreReviews:"加载更多评价",stars:"{count} 星",
  restockLogin:"登录后催补货",restockRequested:"已催补货",requestRestock:"催补货",requestRestockFailed:"催补货失败",peopleRequested:"{count} 人已催",noRestockRequests:"还没人催",moreRequesters:"还有 {count} 人已催补货",requesterAvatar:"{name} 的头像",
  profile:"个人资料",voucherRedeem:"卡券兑换",accountSecurity:"账号与安全",forgotPassword:"忘记密码？",email:"邮箱",sendVerificationCode:"发送验证码",completeVerification:"完成验证",changeEmail:"修改邮箱",emailCodeSent:"验证码已发送至 {email}",
  bindEmailTitle:"绑定邮箱",bindEmailDescription:"用于订单与账号安全通知。",resetPassword:"重置密码",resetPasswordDescription:"输入已验证的邮箱，我们会发送验证码。",resetPasswordSentDescription:"输入验证码并设置新密码。",newPassword:"新密码",currentPassword:"当前密码",confirmNewPassword:"确认新密码",showPassword:"显示密码",hidePassword:"隐藏密码",
  profileDescription:"设置商城中显示的昵称和头像",publicProfile:"公开资料",publicProfileDescription:"自定义后的昵称和头像不会再被第三方登录资料覆盖。",currentAvatar:"当前头像",avatar:"头像",chooseImage:"选择图片",avatarFileHint:"JPG、PNG 或 WebP，最大 2 MB",invalidAvatarType:"请选择 JPG、PNG 或 WebP 图片",avatarTooLarge:"头像文件不能超过 2 MB",boundEmail:"绑定邮箱",saveProfile:"保存资料",
  securityTitle:"账号与安全",securityDescription:"管理密码和登录验证方式",passwordSection:"密码",passwordUpdateHint:"设置强密码并定期更新",passwordCreateHint:"为第三方登录账号设置本地密码",passwordClassesShort:"至少包含 3 类字符",updatePassword:"更新密码",setPassword:"设置密码",twoFactorTitle:"二次验证",twoFactorEnabledStatus:"已开启 · 剩余 {count} 个恢复码",twoFactorDescription:"使用验证器 App 生成一次性验证码",saveRecoveryCodes:"请立即保存恢复码",recoveryCodesHint:"每个恢复码只能使用一次；丢失验证器时可用于登录。",recoveryCodesCopied:"恢复码已复制",copyRecoveryCodes:"复制恢复码",configureAuthenticator:"配置验证器 App",scanAuthenticatorQr:"使用 Google Authenticator、Microsoft Authenticator 或 1Password 扫描二维码",manualSecret:"无法扫描？手动输入密钥：",authenticatorCodeLabel:"输入验证器中的 6 位验证码",enableTwoFactor:"确认开启",disableTwoFactorHint:"关闭前，请输入验证器验证码或一组恢复码。",twoFactorCodeOrRecovery:"6 位验证码或恢复码",disableTwoFactor:"关闭二次验证",verifyTwoFactorTitle:"二次验证",verifyTwoFactorDescription:"输入验证器验证码或恢复码以继续。",verifyAndContinue:"验证并继续",
  walletTitle:"余额与充值",walletDescription:"管理可用余额、充值赠送与会员积分",cnyAccountMember:"CNY 账户 · 会员编号 {number}",cashBalance:"现金余额",bonusBalance:"奖励金",memberPoints:"会员积分",lifetimeSpend:"累计有效消费 {amount}",distanceToTier:"距 {tier}",highestTier:"最高等级",amountRemaining:"还差 {amount}",unlocked:"已解锁",membershipProgress:"会员等级进度",topupBalance:"充值余额",topupBalanceHint:"到账后可直接用于商城支付",topupBonusCurrent:"本次充值赠送 1% 奖励金",topupAutoCredit:"支付完成后余额将自动到账",externalPurchase:"第三方平台购买",externalPurchaseHint:"购买卡券后，在“卡券兑换”中充值到账。",topupBenefit:"充值赠送",topupBenefitDescription:"每次充值额外获得 1% 奖励金。",pointsDiscount:"积分抵扣",pointsDiscountDescription:"实付 ¥1 获得 1 积分；200 积分抵 ¥1，单笔最高抵 10%。",accountActivity:"账户动态",accountActivityDescription:"资金与会员权益的最近变动",memberBenefits:"会员权益",noBenefitRecords:"暂无会员权益记录",balanceLabel:"余额",tierStarter:"黑铁会员",tierSilver:"银耀会员",tierGold:"金耀会员",tierObsidian:"黑曜会员",
  voucherTitle:"卡券兑换",voucherDescription:"输入从合作平台购买的卡券码，兑换到账户或商品。",voucherCode:"卡券码",redeemNow:"立即兑换",rechargeVoucher:"充值券",rechargeVoucherDescription:"兑换后直接到账",productVoucher:"商品兑换券",productVoucherDescription:"直接兑换指定商品",discountVoucher:"满减券",discountVoucherDescription:"存入账号，结算时使用",myVouchers:"我的卡券",myVouchersDescription:"已兑换的卡券与使用状态。",noVouchers:"暂无已兑换卡券",voucherCreditAmount:"到账 {amount}",specifiedProduct:"指定商品",voucherDiscountDetail:"满 {minimum} 减 {discount}",voucherExpired:"已过期",voucherReady:"待使用",voucherReserved:"订单处理中",voucherUsed:"已使用",validUntil:"有效至 {date}",
  guestCheckoutRequired:"填写接收订单通知的邮箱并完成人机验证后即可购买",usePoints:"使用积分（现有 {count}）",pointsRule:"200 积分抵 ¥1，单笔最多抵扣 10%",noDiscountVoucher:"不使用满减券",voucherApplied:"本单已减 {amount}",voucherAmountRemaining:"还差 {amount} 可使用",voucherDiscountApplied:"已使用满减券 -{amount}",deliveryProtected:"卡密已受二次验证保护",verifyToView:"验证后查看",
  imagePreview:"图片预览",imagePreviewDescription:"放大查看商品详情图片，按 Escape 键关闭。",productImage:"商品图片",announcementGoTo:"切换到第 {index} 条公告",settledAs:"结算",startsAt:"起",
  previewTitle:"商品临时预览",previewExpires:"此页面不会上架商品或开放购买，将在 {date} 后失效。",featured:"推荐",previewUnavailable:"预览模式不可购买",
  storeMetaTitle:"{site} - 数字商品商城",storeMetaDescription:"在 {site} 安全购买数字商品、软件与 AI 服务。",
  termsTitle:"服务条款",termsIntro:"本页面说明在 Game3DTech 浏览、购买数字商品及使用账户服务时适用的基本规则。",termsAccountTitle:"账户与信息",termsAccountBody:"请提供真实、有效的账户和联系方式，并妥善保管登录凭证。账户内发生的操作以平台记录为准。",termsDeliveryTitle:"商品与交付",termsDeliveryBody:"商品页面会展示价格、规格、预计交付方式和库存状态。付款前请确认商品说明；数字商品一经交付，请及时核验并安全保存。",termsPaymentTitle:"支付与余额",termsPaymentBody:"支付、余额充值和消费记录可在账户页面查询。若订单状态与实际支付不一致，请保留订单号并联系在线客服核验。",termsUseTitle:"合理使用",termsUseBody:"不得利用本站从事欺诈、滥用、攻击系统或侵犯第三方权益的行为。违规操作可能导致订单暂停或账户限制。",
  privacyTitle:"隐私说明",privacyIntro:"我们只处理提供账户、订单、支付、交付与客服所需的信息。",privacyCollectionTitle:"收集的信息",privacyCollectionBody:"包括登录标识、已验证邮箱、订单和余额记录、客服会话，以及保障服务安全所需的基础技术日志。第三方登录只获取授权页面明确展示的信息。",privacyPurposeTitle:"使用目的",privacyPurposeBody:"用于身份验证、订单履行、支付核验、重要通知、售后支持、防止欺诈和改进服务。未经单独同意，不会用于发送营销垃圾邮件。",privacyRetentionTitle:"保存与保护",privacyRetentionBody:"我们会根据业务、安全和合规需要保留必要记录，并采用访问控制等措施限制未授权访问。请勿在客服消息中发送密码、完整支付凭证或其他不必要的敏感信息。",privacyChoicesTitle:"你的选择",privacyChoicesBody:"你可以在账户页面维护个人资料与安全设置；如需查询、更正或删除相关信息，可通过在线客服提交请求。",
  refundTitle:"退款与售后",refundIntro:"数字商品具有即时交付和可复制的特性，售后将结合商品状态与实际交付情况处理。",refundSubmitTitle:"提交申请",refundSubmitBody:"登录后可在“我的订单”中选择对应订单提交退款申请，并说明具体原因；也可以通过在线客服补充订单号和问题描述。",refundUndeliveredTitle:"尚未交付",refundUndeliveredBody:"未完成支付或尚未交付的订单，将根据支付状态、库存占用和订单进度进行核验处理。",refundDeliveredTitle:"已经交付",refundDeliveredBody:"已展示、复制或发送的卡密及数字权益通常无法直接恢复。若存在无法使用、与描述不符或重复扣款等情况，请尽快提交证据，我们会逐单核验。",refundResultTitle:"处理结果",refundResultBody:"审核进度与结果会记录在订单中。获批退款将按实际支付渠道或账户余额处理，具体到账时间取决于支付渠道。",legalUpdated:"更新日期：2026 年 7 月 19 日",backToStore:"返回商城",
  supportChat:"聊天",supportQuestion:"有疑问吗？联系我们",supportOnline:"客服在线",supportAway:"暂时离开 · 通常一小时内回复",supportConnecting:"连接中…",supportWelcome:"你好！请问有什么可以帮助你了解 {site}？",supportPlaceholder:"输入你的信息…",sendMessage:"发送消息",openSupport:"打开在线客服",closeChat:"关闭聊天",minimizeChat:"最小化聊天",realtimeConnected:"实时连接",realtimeDisconnected:"正在重新连接…",
};

export const partialTranslations: Record<Exclude<Locale,"en"|"zh">, Partial<Record<MessageKey,string>>> = {
  ja: { language:"言語",displayCurrency:"表示通貨",close:"閉じる",search:"検索",searchProducts:"商品を検索…",leaderboard:"購入者ランキング",myOrders:"注文履歴",wallet:"残高・チャージ",logout:"ログアウト",login:"ログイン",register:"登録",allProducts:"すべての商品",noProducts:"商品はまだありません",comeBackLater:"後でもう一度ご確認ください",popular:"人気",soldOut:"売り切れ",wantRestock:"再入荷をご希望ですか？",view:"表示",sold:"{count}件販売",onlyLeft:"残り{count}件",footerTagline:"デジタル商品とスマートサービス",footerSecurePayment:"安全な支払い",footerFastDelivery:"迅速な配送",footerMultilingual:"多言語対応",footerNavigation:"ストア情報",footerTerms:"利用規約",footerPrivacy:"プライバシー",footerRefunds:"返金・サポート",acceptedPayments:"対応する支払い方法",loginTitle:"ログインまたはアカウント作成",loginDescription:"購入、注文確認、残高管理にはログインしてください",orEmail:"またはメールを使用",password:"パスワード",nickname:"表示名",confirmPassword:"パスワード確認",emailLogin:"メールでログイン",createAccount:"アカウント作成",availableBalance:"利用可能残高",topupAmount:"チャージ金額",topupNow:"今すぐチャージ",balanceHistory:"残高履歴",noBalanceRecords:"履歴はありません",ordersTitle:"注文履歴",noOrders:"注文はありません",orderNo:"注文番号",product:"商品",amount:"金額",status:"状態",details:"詳細",previous:"前へ",next:"次へ",searchTitle:"商品検索",allCategories:"すべてのカテゴリ",noSearchResults:"商品が見つかりません",rank:"順位",customer:"お客様",completedOrders:"完了した注文",totalSpent:"合計購入額",noData:"データなし",buyNow:"今すぐ購入",outOfStock:"在庫切れ",quantity:"数量",total:"合計",submitOrder:"注文する",paymentSuccess:"支払い完了",paymentPending:"支払い待ち",paymentFailed:"支払い失敗",backHome:"ストアへ戻る",viewOrders:"注文を見る",loading:"読み込み中…",supportChat:"チャット",supportQuestion:"ご質問がありますか？",supportOnline:"オンライン · 通常1時間以内に返信",supportConnecting:"接続中…",supportWelcome:"こんにちは！{site}についてどのようにお手伝いできますか？",supportPlaceholder:"メッセージを入力…",sendMessage:"送信",openSupport:"サポートを開く",closeChat:"チャットを閉じる",minimizeChat:"最小化",realtimeConnected:"接続済み",realtimeDisconnected:"再接続中…" },
  es: { language:"Idioma",displayCurrency:"Moneda mostrada",close:"Cerrar",search:"Buscar",searchProducts:"Buscar productos…",leaderboard:"Clasificación de clientes",myOrders:"Mis pedidos",wallet:"Saldo y recarga",logout:"Cerrar sesión",login:"Iniciar sesión",register:"Registrarse",allProducts:"Todos los productos",noProducts:"Aún no hay productos",comeBackLater:"Vuelve más tarde",popular:"Popular",soldOut:"Agotado",wantRestock:"¿Quieres reposición?",view:"Ver",sold:"{count} vendidos",onlyLeft:"Solo quedan {count}",footerTagline:"Productos digitales y servicios inteligentes",footerSecurePayment:"Pago seguro",footerFastDelivery:"Entrega rápida",footerMultilingual:"Multilingüe",footerNavigation:"Información de la tienda",footerTerms:"Términos",footerPrivacy:"Privacidad",footerRefunds:"Reembolsos y soporte",acceptedPayments:"Métodos de pago aceptados",loginTitle:"Inicia sesión o crea una cuenta",loginDescription:"Inicia sesión para comprar, consultar pedidos y gestionar tu saldo",orEmail:"o usa el correo",password:"Contraseña",nickname:"Nombre visible",confirmPassword:"Confirmar contraseña",emailLogin:"Entrar con correo",createAccount:"Crear cuenta",availableBalance:"Saldo disponible",topupAmount:"Importe de recarga",topupNow:"Recargar ahora",balanceHistory:"Historial de saldo",noBalanceRecords:"Sin movimientos",ordersTitle:"Mis pedidos",noOrders:"Aún no hay pedidos",orderNo:"Número de pedido",product:"Producto",amount:"Importe",status:"Estado",details:"Detalles",previous:"Anterior",next:"Siguiente",searchTitle:"Buscar productos",allCategories:"Todas las categorías",noSearchResults:"No se encontraron productos",rank:"Puesto",customer:"Cliente",completedOrders:"Pedidos completados",totalSpent:"Gasto total",noData:"Sin datos",buyNow:"Comprar ahora",outOfStock:"Agotado",quantity:"Cantidad",total:"Total",submitOrder:"Realizar pedido",paymentSuccess:"Pago realizado",paymentPending:"Pago pendiente",paymentFailed:"Pago fallido",backHome:"Volver a la tienda",viewOrders:"Ver pedidos",loading:"Cargando…",supportChat:"Chat",supportQuestion:"¿Tienes preguntas?",supportOnline:"En línea · respuesta habitual en una hora",supportConnecting:"Conectando…",supportWelcome:"¡Hola! ¿Cómo podemos ayudarte con {site}?",supportPlaceholder:"Escribe tu mensaje…",sendMessage:"Enviar",openSupport:"Abrir soporte",closeChat:"Cerrar chat",minimizeChat:"Minimizar",realtimeConnected:"Conectado",realtimeDisconnected:"Reconectando…" },
  pt: { language:"Idioma",displayCurrency:"Moeda exibida",close:"Fechar",search:"Pesquisar",searchProducts:"Pesquisar produtos…",leaderboard:"Ranking de clientes",myOrders:"Meus pedidos",wallet:"Saldo e recarga",logout:"Sair",login:"Entrar",register:"Cadastrar",allProducts:"Todos os produtos",noProducts:"Ainda não há produtos",comeBackLater:"Volte mais tarde",popular:"Popular",soldOut:"Esgotado",wantRestock:"Quer reposição?",view:"Ver",sold:"{count} vendidos",onlyLeft:"Restam apenas {count}",footerTagline:"Produtos digitais e serviços inteligentes",footerSecurePayment:"Pagamento seguro",footerFastDelivery:"Entrega rápida",footerMultilingual:"Multilíngue",footerNavigation:"Informações da loja",footerTerms:"Termos",footerPrivacy:"Privacidade",footerRefunds:"Reembolsos e suporte",acceptedPayments:"Formas de pagamento aceitas",loginTitle:"Entre ou crie uma conta",loginDescription:"Entre para comprar, acompanhar pedidos e gerenciar seu saldo",orEmail:"ou use o e-mail",password:"Senha",nickname:"Nome de exibição",confirmPassword:"Confirmar senha",emailLogin:"Entrar com e-mail",createAccount:"Criar conta",availableBalance:"Saldo disponível",topupAmount:"Valor da recarga",topupNow:"Recarregar agora",balanceHistory:"Histórico do saldo",noBalanceRecords:"Sem movimentações",ordersTitle:"Meus pedidos",noOrders:"Ainda não há pedidos",orderNo:"Número do pedido",product:"Produto",amount:"Valor",status:"Status",details:"Detalhes",previous:"Anterior",next:"Próximo",searchTitle:"Pesquisar produtos",allCategories:"Todas as categorias",noSearchResults:"Nenhum produto encontrado",rank:"Posição",customer:"Cliente",completedOrders:"Pedidos concluídos",totalSpent:"Total gasto",noData:"Sem dados",buyNow:"Comprar agora",outOfStock:"Esgotado",quantity:"Quantidade",total:"Total",submitOrder:"Fazer pedido",paymentSuccess:"Pagamento concluído",paymentPending:"Pagamento pendente",paymentFailed:"Falha no pagamento",backHome:"Voltar à loja",viewOrders:"Ver pedidos",loading:"Carregando…",supportChat:"Chat",supportQuestion:"Alguma dúvida?",supportOnline:"Online · resposta geralmente em até uma hora",supportConnecting:"Conectando…",supportWelcome:"Olá! Como podemos ajudar com {site}?",supportPlaceholder:"Digite sua mensagem…",sendMessage:"Enviar",openSupport:"Abrir suporte",closeChat:"Fechar chat",minimizeChat:"Minimizar",realtimeConnected:"Conectado",realtimeDisconnected:"Reconectando…" },
  ko: { language:"언어",close:"닫기",search:"검색",searchProducts:"상품 검색…",leaderboard:"고객 순위",myOrders:"내 주문",wallet:"잔액 및 충전",logout:"로그아웃",login:"로그인",register:"가입",allProducts:"전체 상품",noProducts:"상품이 없습니다",comeBackLater:"나중에 다시 확인해 주세요",popular:"인기",soldOut:"품절",wantRestock:"재입고를 원하시나요?",view:"보기",sold:"{count}개 판매",onlyLeft:"{count}개 남음",footerDisclaimer:"이 사이트는 Linux DO 공식 사이트와 관련이 없습니다.",footerTagline:"디지털 상품과 스마트 서비스",footerSecurePayment:"안전 결제",footerFastDelivery:"빠른 배송",footerMultilingual:"다국어 지원",loginTitle:"로그인 또는 계정 만들기",loginDescription:"로그인하여 상품 구매, 주문 조회 및 잔액 관리를 이용하세요",orEmail:"또는 이메일 사용",password:"비밀번호",nickname:"닉네임",confirmPassword:"비밀번호 확인",emailLogin:"이메일로 로그인",createAccount:"계정 만들기",availableBalance:"사용 가능 잔액",topupAmount:"충전 금액",topupNow:"지금 충전",balanceHistory:"잔액 내역",noBalanceRecords:"잔액 기록 없음",ordersTitle:"내 주문",noOrders:"주문이 없습니다",orderNo:"주문 번호",product:"상품",amount:"금액",status:"상태",details:"상세",previous:"이전",next:"다음",searchTitle:"상품 검색",allCategories:"전체 카테고리",noSearchResults:"검색 결과 없음",rank:"순위",customer:"고객",completedOrders:"완료 주문",totalSpent:"총 지출",noData:"데이터 없음",buyNow:"지금 구매",outOfStock:"품절",quantity:"수량",total:"합계",submitOrder:"주문 제출",paymentSuccess:"결제 성공",paymentPending:"결제 대기",paymentFailed:"결제 실패",backHome:"스토어로 돌아가기",viewOrders:"주문 보기",loading:"로딩 중…",supportChat:"채팅",supportQuestion:"궁금한 점이 있나요? 문의하세요",supportOnline:"온라인 · 보통 1시간 내 답변",supportConnecting:"연결 중…",supportWelcome:"안녕하세요! {site}에 대해 무엇을 도와드릴까요?",supportPlaceholder:"메시지를 입력하세요…",sendMessage:"메시지 보내기",openSupport:"고객 지원 열기",closeChat:"채팅 닫기",minimizeChat:"채팅 최소화",realtimeConnected:"실시간 연결",realtimeDisconnected:"재연결 중…" },
  ru: { language:"Язык",close:"Закрыть",search:"Поиск",searchProducts:"Поиск товаров…",leaderboard:"Рейтинг покупателей",myOrders:"Мои заказы",wallet:"Баланс и пополнение",logout:"Выйти",login:"Войти",register:"Регистрация",allProducts:"Все товары",noProducts:"Товаров пока нет",comeBackLater:"Загляните позже",popular:"Популярное",soldOut:"Распродано",wantRestock:"Ждёте поступления?",view:"Открыть",sold:"Продано: {count}",onlyLeft:"Осталось: {count}",footerDisclaimer:"Сайт не связан с официальным Linux DO.",footerTagline:"Цифровые товары и интеллектуальные сервисы",footerSecurePayment:"Безопасная оплата",footerFastDelivery:"Быстрая доставка",footerMultilingual:"Несколько языков",loginTitle:"Вход или регистрация",loginDescription:"Войдите для покупок, просмотра заказов и управления балансом",orEmail:"или Email",password:"Пароль",nickname:"Имя",confirmPassword:"Повторите пароль",emailLogin:"Войти по Email",createAccount:"Создать аккаунт",availableBalance:"Доступный баланс",topupAmount:"Сумма пополнения",topupNow:"Пополнить",balanceHistory:"История баланса",noBalanceRecords:"Операций нет",ordersTitle:"Мои заказы",noOrders:"Заказов пока нет",orderNo:"Номер заказа",product:"Товар",amount:"Сумма",status:"Статус",details:"Подробнее",previous:"Назад",next:"Далее",searchTitle:"Поиск товаров",allCategories:"Все категории",noSearchResults:"Ничего не найдено",rank:"Место",customer:"Покупатель",completedOrders:"Завершённые заказы",totalSpent:"Всего потрачено",noData:"Нет данных",buyNow:"Купить",outOfStock:"Нет в наличии",quantity:"Количество",total:"Итого",submitOrder:"Оформить заказ",paymentSuccess:"Оплата успешна",paymentPending:"Ожидание оплаты",paymentFailed:"Ошибка оплаты",backHome:"Вернуться в магазин",viewOrders:"Посмотреть заказы",loading:"Загрузка…",supportChat:"Чат",supportQuestion:"Есть вопросы? Напишите нам",supportOnline:"Онлайн · обычно отвечаем в течение часа",supportConnecting:"Подключение…",supportWelcome:"Здравствуйте! Чем помочь по {site}?",supportPlaceholder:"Введите сообщение…",sendMessage:"Отправить",openSupport:"Открыть поддержку",closeChat:"Закрыть чат",minimizeChat:"Свернуть чат",realtimeConnected:"Онлайн-соединение",realtimeDisconnected:"Переподключение…" },
  de: { language:"Sprache",close:"Schließen",search:"Suchen",searchProducts:"Produkte suchen…",leaderboard:"Kundenrangliste",myOrders:"Meine Bestellungen",wallet:"Guthaben & Aufladen",logout:"Abmelden",login:"Anmelden",register:"Registrieren",allProducts:"Alle Produkte",noProducts:"Noch keine Produkte",comeBackLater:"Bitte später wiederkommen",popular:"Beliebt",soldOut:"Ausverkauft",wantRestock:"Nachschub gewünscht?",view:"Ansehen",sold:"{count} verkauft",onlyLeft:"Nur noch {count}",footerDisclaimer:"Diese Website ist nicht mit Linux DO verbunden.",footerTagline:"Digitale Produkte und intelligente Services",footerSecurePayment:"Sichere Zahlung",footerFastDelivery:"Schnelle Lieferung",footerMultilingual:"Mehrsprachig",loginTitle:"Anmelden oder Konto erstellen",loginDescription:"Anmelden, um zu kaufen, Bestellungen anzusehen und Guthaben zu verwalten",orEmail:"oder Email verwenden",password:"Passwort",nickname:"Anzeigename",confirmPassword:"Passwort bestätigen",emailLogin:"Mit Email anmelden",createAccount:"Konto erstellen",availableBalance:"Verfügbares Guthaben",topupAmount:"Aufladebetrag",topupNow:"Jetzt aufladen",balanceHistory:"Guthabenverlauf",noBalanceRecords:"Keine Einträge",ordersTitle:"Meine Bestellungen",noOrders:"Noch keine Bestellungen",orderNo:"Bestellnummer",product:"Produkt",amount:"Betrag",status:"Status",details:"Details",previous:"Zurück",next:"Weiter",searchTitle:"Produkte suchen",allCategories:"Alle Kategorien",noSearchResults:"Keine Produkte gefunden",rank:"Rang",customer:"Kunde",completedOrders:"Abgeschlossene Bestellungen",totalSpent:"Gesamtausgaben",noData:"Keine Daten",buyNow:"Jetzt kaufen",outOfStock:"Nicht verfügbar",quantity:"Menge",total:"Gesamt",submitOrder:"Bestellung absenden",paymentSuccess:"Zahlung erfolgreich",paymentPending:"Zahlung ausstehend",paymentFailed:"Zahlung fehlgeschlagen",backHome:"Zurück zum Shop",viewOrders:"Bestellungen ansehen",loading:"Laden…",supportChat:"Chat",supportQuestion:"Fragen? Schreiben Sie uns",supportOnline:"Online · Antwort meist innerhalb einer Stunde",supportConnecting:"Verbindung…",supportWelcome:"Hallo! Wie können wir bei {site} helfen?",supportPlaceholder:"Nachricht eingeben…",sendMessage:"Senden",openSupport:"Kundenservice öffnen",closeChat:"Chat schließen",minimizeChat:"Chat minimieren",realtimeConnected:"Live verbunden",realtimeDisconnected:"Verbindung wird wiederhergestellt…" },
  id: { language:"Bahasa",close:"Tutup",search:"Cari",searchProducts:"Cari produk…",leaderboard:"Peringkat pelanggan",myOrders:"Pesanan saya",wallet:"Saldo & isi ulang",logout:"Keluar",login:"Masuk",register:"Daftar",allProducts:"Semua produk",noProducts:"Belum ada produk",comeBackLater:"Silakan kembali lagi",popular:"Populer",soldOut:"Habis",wantRestock:"Ingin stok kembali?",view:"Lihat",sold:"{count} terjual",onlyLeft:"Tersisa {count}",footerDisclaimer:"Situs ini tidak berafiliasi dengan Linux DO.",footerTagline:"Produk digital dan layanan cerdas",footerSecurePayment:"Pembayaran aman",footerFastDelivery:"Pengiriman cepat",footerMultilingual:"Multibahasa",loginTitle:"Masuk atau buat akun",loginDescription:"Masuk untuk membeli, melihat pesanan, dan mengelola saldo",orEmail:"atau gunakan Email",password:"Kata sandi",nickname:"Nama tampilan",confirmPassword:"Konfirmasi kata sandi",emailLogin:"Masuk dengan Email",createAccount:"Buat akun",availableBalance:"Saldo tersedia",topupAmount:"Jumlah isi ulang",topupNow:"Isi ulang",balanceHistory:"Riwayat saldo",noBalanceRecords:"Belum ada catatan",ordersTitle:"Pesanan saya",noOrders:"Belum ada pesanan",orderNo:"Nomor pesanan",product:"Produk",amount:"Jumlah",status:"Status",details:"Detail",previous:"Sebelumnya",next:"Berikutnya",searchTitle:"Cari produk",allCategories:"Semua kategori",noSearchResults:"Produk tidak ditemukan",rank:"Peringkat",customer:"Pelanggan",completedOrders:"Pesanan selesai",totalSpent:"Total belanja",noData:"Tidak ada data",buyNow:"Beli sekarang",outOfStock:"Stok habis",quantity:"Jumlah",total:"Total",submitOrder:"Buat pesanan",paymentSuccess:"Pembayaran berhasil",paymentPending:"Menunggu pembayaran",paymentFailed:"Pembayaran gagal",backHome:"Kembali ke toko",viewOrders:"Lihat pesanan",loading:"Memuat…",supportChat:"Chat",supportQuestion:"Ada pertanyaan? Hubungi kami",supportOnline:"Online · biasanya membalas dalam satu jam",supportConnecting:"Menghubungkan…",supportWelcome:"Halo! Ada yang bisa kami bantu tentang {site}?",supportPlaceholder:"Ketik pesan Anda…",sendMessage:"Kirim pesan",openSupport:"Buka layanan pelanggan",closeChat:"Tutup chat",minimizeChat:"Minimalkan chat",realtimeConnected:"Terhubung langsung",realtimeDisconnected:"Menghubungkan kembali…" },
  hi: { language:"भाषा",close:"बंद करें",search:"खोजें",searchProducts:"उत्पाद खोजें…",leaderboard:"ग्राहक रैंकिंग",myOrders:"मेरे ऑर्डर",wallet:"बैलेंस और रिचार्ज",logout:"साइन आउट",login:"साइन इन",register:"रजिस्टर",allProducts:"सभी उत्पाद",noProducts:"अभी कोई उत्पाद नहीं",comeBackLater:"कृपया बाद में देखें",popular:"लोकप्रिय",soldOut:"स्टॉक समाप्त",wantRestock:"दोबारा स्टॉक चाहिए?",view:"देखें",sold:"{count} बिके",onlyLeft:"केवल {count} बचे",footerDisclaimer:"यह साइट Linux DO से संबद्ध नहीं है।",footerTagline:"डिजिटल उत्पाद और स्मार्ट सेवाएँ",footerSecurePayment:"सुरक्षित भुगतान",footerFastDelivery:"तेज़ डिलीवरी",footerMultilingual:"बहुभाषी सहायता",loginTitle:"साइन इन करें या खाता बनाएँ",loginDescription:"खरीदारी, ऑर्डर और बैलेंस के लिए साइन इन करें",orEmail:"या Email का उपयोग करें",password:"पासवर्ड",nickname:"डिस्प्ले नाम",confirmPassword:"पासवर्ड की पुष्टि",emailLogin:"Email से साइन इन",createAccount:"खाता बनाएँ",availableBalance:"उपलब्ध बैलेंस",topupAmount:"रिचार्ज राशि",topupNow:"अभी रिचार्ज करें",balanceHistory:"बैलेंस इतिहास",noBalanceRecords:"कोई रिकॉर्ड नहीं",ordersTitle:"मेरे ऑर्डर",noOrders:"अभी कोई ऑर्डर नहीं",orderNo:"ऑर्डर नंबर",product:"उत्पाद",amount:"राशि",status:"स्थिति",details:"विवरण",previous:"पिछला",next:"अगला",searchTitle:"उत्पाद खोजें",allCategories:"सभी श्रेणियाँ",noSearchResults:"कोई उत्पाद नहीं मिला",rank:"रैंक",customer:"ग्राहक",completedOrders:"पूरे ऑर्डर",totalSpent:"कुल खर्च",noData:"कोई डेटा नहीं",buyNow:"अभी खरीदें",outOfStock:"स्टॉक समाप्त",quantity:"मात्रा",total:"कुल",submitOrder:"ऑर्डर करें",paymentSuccess:"भुगतान सफल",paymentPending:"भुगतान लंबित",paymentFailed:"भुगतान विफल",backHome:"स्टोर पर वापस जाएँ",viewOrders:"ऑर्डर देखें",loading:"लोड हो रहा है…",supportChat:"चैट",supportQuestion:"कोई सवाल? हमसे बात करें",supportOnline:"ऑनलाइन · आमतौर पर एक घंटे में जवाब",supportConnecting:"कनेक्ट हो रहा है…",supportWelcome:"नमस्ते! {site} के बारे में हम कैसे मदद करें?",supportPlaceholder:"अपना संदेश लिखें…",sendMessage:"संदेश भेजें",openSupport:"ग्राहक सहायता खोलें",closeChat:"चैट बंद करें",minimizeChat:"चैट छोटा करें",realtimeConnected:"लाइव कनेक्शन",realtimeDisconnected:"फिर से कनेक्ट हो रहा है…" },
};

export const translationOverrides: Partial<
  Record<Exclude<Locale, "en" | "zh">, Partial<Record<MessageKey, string>>>
> = {
  ja: {
    leaderboard: "売れ筋ランキング",
    leaderboardDescription: "完了した注文の商品販売数順",
    requestRestock: "再入荷を依頼",
    restockRequested: "再入荷を依頼済み",
    requestRestockFailed: "再入荷依頼に失敗しました",
    peopleRequested: "{count}人が再入荷を希望",
    backToStore: "ストアへ戻る",
    memberRechargeBenefitTitle: "会員チャージ特典",
    memberRechargeBenefit: "アカウントを作成すると、残高チャージごとに1%のボーナスクレジットを獲得できます。",
    toggleTheme: "テーマを切り替え", lightTheme: "ライト", darkTheme: "ダーク", systemTheme: "システム設定",
  },
  es: {
    leaderboard: "Más vendidos",
    leaderboardDescription: "Productos ordenados por ventas completadas",
    requestRestock: "Solicitar reposición",
    restockRequested: "Reposición solicitada",
    requestRestockFailed: "No se pudo solicitar la reposición",
    peopleRequested: "{count} personas solicitaron reposición",
    toggleTheme: "Cambiar tema", lightTheme: "Claro", darkTheme: "Oscuro", systemTheme: "Sistema",
  },
  pt: {
    leaderboard: "Mais vendidos",
    leaderboardDescription: "Produtos classificados por vendas concluídas",
    requestRestock: "Solicitar reposição",
    restockRequested: "Reposição solicitada",
    requestRestockFailed: "Não foi possível solicitar reposição",
    peopleRequested: "{count} pessoas solicitaram reposição",
    toggleTheme: "Alterar tema", lightTheme: "Claro", darkTheme: "Escuro", systemTheme: "Sistema",
  },
  ko: {
    leaderboard: "베스트셀러",
    leaderboardDescription: "완료된 주문의 상품 판매량 순위",
    toggleTheme: "테마 전환", lightTheme: "라이트", darkTheme: "다크", systemTheme: "시스템",
  },
  ru: {
    leaderboard: "Хиты продаж",
    leaderboardDescription: "Товары по количеству завершённых продаж",
    toggleTheme: "Сменить тему", lightTheme: "Светлая", darkTheme: "Тёмная", systemTheme: "Системная",
  },
  de: {
    leaderboard: "Bestseller",
    leaderboardDescription: "Produkte nach abgeschlossenen Verkäufen",
    toggleTheme: "Design wechseln", lightTheme: "Hell", darkTheme: "Dunkel", systemTheme: "System",
  },
  id: {
    leaderboard: "Produk terlaris",
    leaderboardDescription: "Produk diurutkan berdasarkan penjualan selesai",
    toggleTheme: "Ganti tema", lightTheme: "Terang", darkTheme: "Gelap", systemTheme: "Sistem",
  },
  hi: {
    leaderboard: "सर्वाधिक बिकने वाले",
    leaderboardDescription: "पूरी हुई बिक्री के आधार पर उत्पाद रैंकिंग",
    toggleTheme: "थीम बदलें", lightTheme: "हल्का", darkTheme: "गहरा", systemTheme: "सिस्टम",
  },
};

export function detectLocale(value: string | null | undefined): Locale {
  const normalized = value?.toLowerCase() || "";
  if (normalized.startsWith("zh")) return "zh";
  if (normalized.startsWith("ja")) return "ja";
  if (normalized.startsWith("ko")) return "ko";
  if (normalized.startsWith("es")) return "es";
  if (normalized.startsWith("pt")) return "pt";
  if (normalized.startsWith("ru")) return "ru";
  if (normalized.startsWith("de")) return "de";
  if (normalized.startsWith("id")) return "id";
  if (normalized.startsWith("hi")) return "hi";
  return "en";
}

export function translate(locale: Locale, key: MessageKey, params?: Record<string,string|number>) {
  const template = locale === "zh"
    ? zhMessages[key]
    : locale === "en"
      ? enMessages[key]
      : generatedTranslations[locale][key] || translationOverrides[locale]?.[key] || partialTranslations[locale][key] || enMessages[key];
  return Object.entries(params || {}).reduce((text,[name,value]) => text.replaceAll(`{${name}}`,String(value)), template);
}
